title: Danielle Marshall # your name (or website title) here

logo: "/images/LinkedInPhoto.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
 M.S Environmental Science, Texas A&M University-Corpus Christi 
 B.S Biology, Point Loma Nazarene University
 <br><br>
  Contact:
  - marshalldanielleann@gmail.com
  - [My LinkedIn Profile](http://linkedin.com/danielle-a-marshall)
  - [My PowerBI Page](link)
  - [My Tableau Public](link)
  
theme: jekyll-theme-minimal

