title: Danielle Marshall # your name (or website title) here
logo: "/images/LinkedInPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Learn about my projects in SQL, PowerBI, and Tableau. 
  <br><br>
  MSc Environmental Science, <br>
  Texas A&M-University Corpus Christi 
  <br><br>
  BS Biology, <br>
  Point Loma Nazarene University
  <br><br>
  Contact: <br>
  - marshalldaniellann@gmail.com <br>
  - <a href="https://www.linkedin.com/in/danielle-a-marshall">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
