title: Danielle Marshall # your name (or website title) here
logo: "/images/AZ8A8967.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! Here you will find SQL projects similar to ad-hoc requests in the workplace as well as visualization projects using PowerBI and Tableau. If you have any questions feel free to reach out!
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/danielle-a-marshall">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
