title: Danielle Marshall # your name (or website title) here
logo: "/images/LinkedInPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My passion for data analytics was ignited during my research for my master's thesis at Texas A&M University-Corpus Christi. With a solid foundation in statistics and multivariate analysis, I approach data with a go-getter attitude. To further enhance my skill set, I have taught myself SQL, Power Query, Power BI, and Tableau. In addition, I have extensively utilized R and SAS throughout my post-graduate studies.
  <br><br>
  MS Environmental Science, <br>
  Texas A&M-University Corpus Christi <br>
  May 2023
  <br><br>
  BS Biology, <br>
  Point Loma Nazarene University <br>
  December 2019
  <br><br>
  Contact: <br>
  - marshalldaniellann@gmail.com <br>
  - <a href="https://www.linkedin.com/in/danielle-a-marshall">My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal


