title: Danielle Marshall # your name (or website title) here
logo: "/images/LinkedInPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I found my love for data analytics when I was conducting research for my master's thesis at Texas A&M University-Corpus Christi. I have a strong background in statistics and multivariate analysis. I am a self-starter and taught myself SQL, PowerBI, and Tableau. 
  Moreover, I have been using R and SAS extensively throughout my post graduate degree. Learn about my projects in SQL, PowerBI, and Tableau. 
  <br><br>
  MSc Environmental Science, <br>
  Texas A&M-University Corpus Christi 
  <br><br>
  BS Biology, <br>
  Point Loma Nazarene University
  <br><br>
  Contact: <br>
  - marshalldaniellann@gmail.com <br>
  - <a href="https://www.linkedin.com/in/danielle-a-marshall">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

github:
  is_project_page: false
