title: Danielle Eckhardt # your name (or website title) here
logo: "/images/IMG_3786.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS Environmental Science, <br>
  Texas A&M-University Corpus Christi <br>
  May 2023
  <br><br>
  BS Biology, <br>
  Point Loma Nazarene University <br>
  December 2019
  <br><br>
  Contact: <br>
  - danielle-eckhardt@outlook.com <br>
  - <a href="https://www.linkedin.com/in/danielle-a-eckhardt">My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal


